name: Unit-test

on:
  pull_request_target:
    branches:
      - master
      
jobs:
 docker_health_check:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
      
    - name: install requirements
      run: pip install -r requirements.txt
      
    - name: docker login
      uses: docker/login-action@v3
      with:
        username: 81318131
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: build services
      run: docker compose build
      
    - name: run services
      run: docker compose up -d


    # - name: Running Unit-tests
    #   run: pytest tests/
    #   working-directory: ./app 

      
    - name: stop containers
      run: docker compose down
